databases:
  - name: hello_rails8
    plan: starter
    databaseName: hello_rails8
    user: hello_rails8

services:
  - type: web
    name: hello_rails8
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello_rails8
          property: connectionString
      - key: SECRET_KEY_BASE
        generateValue: true
